apiVersion: v1
kind: Service
metadata:
  name: log-analyzer-service
spec:
  type: NodePort # Changed from LoadBalancer for local environment development
  selector:
    app: log-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000